# Generated by Django 4.2.29 on 2026-03-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_banner_alter_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=5),
        ),
    ]
