# Generated by Django 4.2.29 on 2026-04-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_booking_date_booking_showtime_alter_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('movie', 'showtime', 'seat')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
